import { Company, Tender, Consortium, User, Match } from './types'

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    email: 'demo@bantu-bid.com',
    name: 'John Mwansa',
    role: 'supplier',
    companyId: 'company-1',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'user-2',
    email: 'test@supplier.zm',
    name: 'Mary Chipo',
    role: 'admin',
    companyId: 'company-5',
    createdAt: new Date('2024-02-20'),
  },
]

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'company-1',
    name: 'Copper Valley Engineering',
    registrationNumber: 'ZM-2022-001234',
    sector: 'Equipment Manufacturing',
    location: 'Kitwe',
    employees: 45,
    description: 'Leading supplier of mining equipment and spare parts',
    localContentPercentage: 75,
    certifications: ['ISO 9001:2015', 'ISO 45001:2018'],
    capabilities: ['Equipment Supply', 'Manufacturing', 'Installation', 'Training'],
    website: 'www.coppervalley.zm',
    contactPerson: 'John Mwansa',
    contactEmail: 'john@coppervalley.zm',
    contactPhone: '+260212345678',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-07-15'),
  },
  {
    id: 'company-2',
    name: 'Zambia Construction Services',
    registrationNumber: 'ZM-2023-005678',
    sector: 'Construction',
    location: 'Ndola',
    employees: 120,
    description: 'Civil engineering and construction for mining infrastructure',
    localContentPercentage: 85,
    certifications: ['ISO 9001:2015', 'OHSAS 18001'],
    capabilities: ['Civil Works', 'Infrastructure', 'Project Management', 'Safety Management'],
    website: 'www.zamcons.zm',
    contactPerson: 'Mary Chipo',
    contactEmail: 'mary@zamcons.zm',
    contactPhone: '+260213456789',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-07-14'),
  },
  {
    id: 'company-3',
    name: 'Luska Logistics Ltd',
    registrationNumber: 'ZM-2023-009012',
    sector: 'Transportation & Logistics',
    location: 'Lusaka',
    employees: 80,
    description: 'Specialized logistics for mining industry transport',
    localContentPercentage: 70,
    certifications: ['ISO 9001:2015'],
    capabilities: ['Transport', 'Warehouse Management', 'Supply Chain', 'Documentation'],
    website: 'www.luskalogistics.zm',
    contactPerson: 'Peter Kunda',
    contactEmail: 'peter@luskalogistics.zm',
    contactPhone: '+260211234567',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-07-12'),
  },
  {
    id: 'company-4',
    name: 'Copperbelt Safety Solutions',
    registrationNumber: 'ZM-2022-003456',
    sector: 'Safety & Compliance',
    location: 'Mufulira',
    employees: 35,
    description: 'Professional safety training and compliance services',
    localContentPercentage: 90,
    certifications: ['ISO 45001:2018', 'IMTC Accredited'],
    capabilities: ['Safety Training', 'Compliance Audits', 'Risk Assessment', 'Documentation'],
    website: 'www.copperbeltsafety.zm',
    contactPerson: 'Grace Mumba',
    contactEmail: 'grace@copperbeltsafety.zm',
    contactPhone: '+260214567890',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-07-13'),
  },
  {
    id: 'company-5',
    name: 'Konkola Copper Mine',
    registrationNumber: 'ZM-2021-007890',
    sector: 'Mining & Metals',
    location: 'Chingola',
    employees: 280,
    description: 'Large-scale copper mining operator with active procurement and local supplier development programmes',
    localContentPercentage: 92,
    certifications: ['ISO 9001:2015', 'ISO 45001:2018', 'ESG Reporting Ready'],
    capabilities: ['Mining Operations', 'Procurement Governance', 'Compliance Oversight', 'Supplier Development'],
    website: 'www.kcm.zm',
    contactPerson: 'Moses Mbewe',
    contactEmail: 'moses@kcm.zm',
    contactPhone: '+260212345999',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-07-16'),
  },
]

export const MOCK_TENDERS: Tender[] = [
  {
    id: 'tender-1',
    title: 'Copper Processing Equipment Supply and Installation',
    description: 'Supply, delivery, and installation of advanced copper processing equipment for mine expansion project',
    miningSite: 'Konkola Copper Mines',
    sector: 'Equipment',
    budget: 2500000,
    minLocalContent: 75,
    deadline: new Date('2024-08-30'),
    status: 'open',
    requirements: ['ISO 9001 certification', 'Minimum 5 years experience in mining equipment', 'Proven track record with major mines', 'Full warranty and after-sales support'],
    specifications: ['Flotation cells: 50 units', 'Thickeners: 10 units', 'Filtration equipment: 20 units'],
    postedDate: new Date('2024-07-01'),
    postedBy: 'kcm-procurement',
  },
  {
    id: 'tender-2',
    title: 'Civil Works for Tailings Storage Facility Expansion',
    description: 'Design and construction of expanded tailings storage facility with environmental compliance',
    miningSite: 'First Quantum Minerals',
    sector: 'Construction',
    budget: 1800000,
    minLocalContent: 70,
    deadline: new Date('2024-09-15'),
    status: 'open',
    requirements: ['ISO 9001 and ISO 45001 certifications', 'Experience with environmental compliance', 'Mine site experience', 'Project management certification'],
    specifications: ['Earthworks: 2.5 million cubic meters', 'Embankment construction', 'Drainage systems installation'],
    postedDate: new Date('2024-07-05'),
    postedBy: 'fqm-procurement',
  },
  {
    id: 'tender-3',
    title: 'Transportation and Logistics Services',
    description: 'Annual transportation and logistics support for mining operations and supply chain management',
    miningSite: 'Nchanga Mine',
    sector: 'Logistics',
    budget: 950000,
    minLocalContent: 80,
    deadline: new Date('2024-08-20'),
    status: 'closing_soon',
    requirements: ['ISO 9001 certification', 'Fleet management capability', 'GPS tracking systems', 'Insurance coverage for mining materials'],
    specifications: ['Long-haul transport: 10,000 tons/month', 'Equipment transport: specialized vehicles', 'Warehouse storage: 50,000 m²'],
    postedDate: new Date('2024-06-20'),
    postedBy: 'nchanga-procurement',
  },
  {
    id: 'tender-4',
    title: 'Safety Training and Compliance Services',
    description: 'Comprehensive safety training program for 500+ employees and ongoing compliance monitoring',
    miningSite: 'Multiple Sites',
    sector: 'Training',
    budget: 450000,
    minLocalContent: 85,
    deadline: new Date('2024-08-31'),
    status: 'open',
    requirements: ['ISO 45001 certification', 'Accredited training provider status', 'Experience with mining safety', 'Current training materials and resources'],
    specifications: ['Initial training: 20 sessions', 'Refresher courses: quarterly', 'Customized modules per department'],
    postedDate: new Date('2024-07-08'),
    postedBy: 'mines-hr',
  },
  {
    id: 'tender-5',
    title: 'Maintenance and Repair Services',
    description: 'Preventive and corrective maintenance for mining equipment',
    miningSite: 'Chililabombwe',
    sector: 'Maintenance',
    budget: 750000,
    minLocalContent: 75,
    deadline: new Date('2024-08-10'),
    status: 'open',
    requirements: ['ISO 9001 certification', 'Specialized mining equipment expertise', '24/7 emergency response capability'],
    specifications: ['Preventive maintenance: monthly', 'Emergency repairs: within 4 hours', 'Spare parts inventory: minimum 3 months stock'],
    postedDate: new Date('2024-07-10'),
    postedBy: 'chililabombwe-ops',
  },
]

export const MOCK_CONSORTIA: Consortium[] = [
  {
    id: 'consortium-1',
    name: 'Northern Mining Solutions',
    description: 'Equipment supply and installation services for copper mining',
    members: [
      {
        companyId: 'company-1',
        companyName: 'Copper Valley Engineering',
        role: 'leader',
        capabilities: ['Equipment Supply', 'Manufacturing', 'Installation'],
        localContent: 75,
        joinedAt: new Date('2024-06-01'),
      },
      {
        companyId: 'company-3',
        companyName: 'Luska Logistics Ltd',
        role: 'member',
        capabilities: ['Transport', 'Warehouse Management'],
        localContent: 70,
        joinedAt: new Date('2024-06-10'),
      },
    ],
    leader: 'company-1',
    status: 'active',
    localContentPercentage: 72.5,
    combinedCapabilities: ['Equipment Supply', 'Manufacturing', 'Installation', 'Transport', 'Warehouse Management'],
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-07-15'),
  },
  {
    id: 'consortium-2',
    name: 'Integrated Construction & Safety',
    description: 'Complete construction and safety solutions for mining infrastructure',
    members: [
      {
        companyId: 'company-2',
        companyName: 'Zambia Construction Services',
        role: 'leader',
        capabilities: ['Civil Works', 'Infrastructure', 'Project Management'],
        localContent: 85,
        joinedAt: new Date('2024-05-15'),
      },
      {
        companyId: 'company-4',
        companyName: 'Copperbelt Safety Solutions',
        role: 'member',
        capabilities: ['Safety Training', 'Compliance Audits'],
        localContent: 90,
        joinedAt: new Date('2024-05-20'),
      },
    ],
    leader: 'company-2',
    status: 'active',
    localContentPercentage: 87.5,
    combinedCapabilities: ['Civil Works', 'Infrastructure', 'Project Management', 'Safety Training', 'Compliance Audits'],
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-07-10'),
  },
]

export const MOCK_MATCHES: Match[] = [
  {
    id: 'match-1',
    consortiumId: 'consortium-1',
    tenderId: 'tender-1',
    score: 92,
    reason: 'Strong match: Equipment supply and logistics capabilities meet requirements',
    createdAt: new Date('2024-07-15'),
  },
  {
    id: 'match-2',
    consortiumId: 'consortium-1',
    tenderId: 'tender-3',
    score: 85,
    reason: 'Good match: Logistics consortium member provides competitive advantage',
    createdAt: new Date('2024-07-15'),
  },
  {
    id: 'match-3',
    consortiumId: 'consortium-2',
    tenderId: 'tender-2',
    score: 95,
    reason: 'Excellent match: Construction expertise and safety compliance align perfectly',
    createdAt: new Date('2024-07-15'),
  },
  {
    id: 'match-4',
    consortiumId: 'consortium-2',
    tenderId: 'tender-4',
    score: 88,
    reason: 'Strong match: Safety training member provides core competency',
    createdAt: new Date('2024-07-15'),
  },
]
